Add ability to set individual head QKV inputs via hook
neelnanda-io/TransformerLens pull request #139
Opened 2023-01-14 09:19 UTC by epurdy

Disabled by default to save GPU memory.

2023-01-20 00:35 UTC, neelnanda-io requested changes
Thanks for this! Overall looks fairly good, I left some comments for cosmetic changes.

A galaxy brained idea - you *can* broadcast a tensor up to a larger, repeated shape without changing the total GPU memory used, since it just changes the striding on the same underslying memory (the bonus axis has stride=0). So maybe we should implement it like that, so we don't need to have the branching statements for q, k and v. OTOH this is too clever and will probably break something rip.

But yeah, I'm overall torn between this being a useful feature and making the code too ugly, though overall I lean towards this being worth it.

2023-01-20 00:35 UTC, neelnanda-io commented on transformer_lens/HookedTransformer.py
> +    def set_use_attn_input(self, use_attn_input):
set_use_attn_input_hooks seems like a better name (I should probably change use_attn_result too lol)

2023-01-20 00:35 UTC, neelnanda-io commented on transformer_lens/components.py
> +            self.hook_attn_input_q = HookPoint()  # [batch, pos, d_model] OR [batch, pos, head_index, d_model]
Oh man, the shortformer bits of this are really ugly. I weakly lean towards just having this feature only apply to non shortformer positional embeddings...?

2023-01-20 00:35 UTC, neelnanda-io commented on transformer_lens/components.py
> +                resid_pre.unsqueeze(2).expand(-1, -1, self.cfg.n_heads, -1).clone()
Please rewrite to einops

`einops.repeat(resid_pre, "batch pos d_model -> batch pos head_index d_model", head_index=self.cfg.n_heads)` should work and IMO is much more readable

2023-01-20 00:35 UTC, neelnanda-io commented on transformer_lens/components.py
> +        self.hook_input_q = HookPoint()  # [batch, pos, head_index, d_model]
Add comment documenting them

2023-01-20 00:35 UTC, neelnanda-io commented on transformer_lens/components.py
> +            if self.cfg.use_attn_input:
Add comment documenting why this if statement is there

2023-01-28 23:59 UTC, ArthurConmy commented
I implemented this here https://github.com/ArthurConmy/Automatic-Circuit-Discovery in einops. I'm happy to take this if wanted @epurdy ?

2023-01-29 00:01 UTC, ArthurConmy commented
Also, I am in favour of the galaxy brain solution. Note this could apply to `use_attn_result` too: we would just broadcast up `attn_out` to have an extra dimension with `einops.repeat`

(and then if we `set_use_attn_results`, we'd clone the tensor so that there wasn't a stride 0 element in there)

I can explain, if this was unclear

2023-01-29 01:03 UTC, epurdy commented
> I implemented this here https://github.com/ArthurConmy/Automatic-Circuit-Discovery in einops. I'm happy to take this if wanted @epurdy ?

Sure, @ArthurConmy, that would be great.

2023-01-29 03:47 UTC, neelnanda-io commented
Sounds great Arthur, it would be good to include a test that the various
acts are actually stride zero in the expected way, and that you can't use
the hook without setting use_... in the relevant way

On Sun, 29 Jan 2023, 9:04 am Eric Purdy, ***@***.***> wrote:

> I implemented this here
> https://github.com/ArthurConmy/Automatic-Circuit-Discovery in einops. I'm
> happy to take this if wanted @epurdy <https://github.com/epurdy> ?
>
> Sure, @ArthurConmy <https://github.com/ArthurConmy>, that would be great.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/neelnanda-io/TransformerLens/pull/139#issuecomment-1407526902>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ASRPNKNGRJCGZ5GTECZEVM3WUW6YHANCNFSM6AAAAAAT3FQMIQ>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2023-01-29 05:54 UTC, ArthurConmy commented
See https://github.com/neelnanda-io/TransformerLens/pull/158

2023-01-29 05:54 UTC, closed without merging