Added feature for detecting common heads automatically.
neelnanda-io/TransformerLens pull request #235
Opened 2023-04-07 06:32 UTC by JayBaileyCS

# Description

Added a feature for detecting common heads automatically, by using a detection pattern to elementwise multiply across an attention pattern, only keeping the attention you're interested in. There's support for previous token heads, duplicate token heads, and induction heads. Users can also define their own detection_pattern. (For example, in IOI, you could create a detection pattern with a 1 if a given token's word is capitalised and 0 otherwise, allowing you to detect how much attention is paid to the sentence's names)

The feature is self-contained, so it does not break anything else, and has 100% test coverage.

I have not yet documented this feature aside from a docstring in the code itself - open to ideas for how we might want to go about this.

The code is also probably not as optimised as it could be, certainly open to ideas on that!

## Type of change

- [ x ] New feature (non-breaking change which adds functionality)

# Checklist:

- [ x ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ x ] My changes generate no new warnings
- [ x ] I have added tests that prove my fix is effective or that my feature works
- [ x ] New and existing unit tests pass locally with my changes
- [ x ] I have not rewritten tests relating to key interfaces which would affect backward compatibility.

2023-04-07 07:31 UTC, JayBaileyCS commented
https://colab.research.google.com/drive/1NfCi7DP17gWiX1wT-hDDmIHUpZJaaQOm#scrollTo=aU1ReJigXOsH shows it being briefly used.

2023-04-08 07:33 UTC, jbloomAus requested changes
Thanks Jay, this is a valuable contribution. 

Besides the specific points, I was wondering if you could:

- [x] 1. Ensure this functionality is mentioned where relevant in any of the tutorials and if not add a mini tutorial for this feature.
- [ ] 2. Share a notebook or something where you validate the code aligned with analysis done by others (ie: whatever convinced you that your implementation works). 

Much appreciated!

2023-04-08 07:33 UTC, jbloomAus commented on transformer_lens/detect_heads.py
Stuff to add:

- [ ] Docstrings to the get head pattern functions (explain what each is a link if needed, such as to ioi paper)
- [ ] Type hints for return arguments 
- [ ] Example usage (just for detect_head_type) in a form that will be picked up nicely in the docs (see IOI evals dataset example).

2023-04-08 07:33 UTC, jbloomAus commented on tests/unit/test_detect_heads.py
Good stuff!

2023-04-11 04:46 UTC, JayBaileyCS commented on transformer_lens/detect_heads.py
I have now added all these things. Could I get another look?

2023-04-11 04:46 UTC, JayBaileyCS commented
Changes have been added.

2023-04-11 04:52 UTC, jbloomAus commented on transformer_lens/detect_heads.py
great thanks!

2023-04-11 04:52 UTC, jbloomAus approved these changes

2023-04-11 04:53 UTC, jbloomAus commented
Looks great! Thanks Jay!

2023-04-11 04:53 UTC, merged