Fix tiny stories model names
neelnanda-io/TransformerLens pull request #305
Opened 2023-06-04 15:31 UTC by Felhof

Closes #299 
Some of the names used to load tiny-story models were misspelled and so we were unable to load them. This PR fixes the spellings and adds a simple unit test that checks if each model's config can be loaded so that we will notice when the names are changed in the future.

2023-06-04 15:55 UTC, ArthurConmy requested changes
Thanks so much for the quick turn around! This seems correct, I just suggest two formatting changes. Can you implement them?

2023-06-04 15:55 UTC, ArthurConmy commented on tests/unit/test_tinystories.py
> +def test_all_models_exist():
```suggestion
def test_all_tinystories_models_exist():
```

Please move this test to `test_hooked_transformer`

2023-06-04 15:55 UTC, ArthurConmy commented on tests/unit/test_tinystories.py
> +]
```suggestion
from transformer_lens.loading_from_pretrained import OFFICIAL_MODEL_NAMES

TINY_STORIES_MODEL_NAMES = [
    name for name in OFFICIAL_MODEL_NAMES if name.startswith("roneneldan/TinyStories")
]
```

2023-06-04 15:55 UTC, ArthurConmy commented on tests/unit/test_tinystories.py
> +]
(of course with this statement in the HookedTransformer file)

2023-06-05 07:58 UTC, jbloomAus approved these changes

2023-06-05 07:59 UTC, jbloomAus commented
Thanks @Felhof

2023-06-05 10:52 UTC, ArthurConmy commented
The acceptance test worked on my local machine, thanks @Felhof :raised_hands: !

2023-06-05 10:52 UTC, merged