Set IGNORE value in mask to -torch.inf
neelnanda-io/TransformerLens pull request #319
Opened 2023-06-10 16:35 UTC by neelnanda-io

# Description

Fixes #318 - In pythia-70m, attn_scores can get below -1e5 (for some reason...). Masked attn scores are set to -1e5, so this makes the model attend outside the mask! This is dumb, and so I set things to -torch.inf instead. It's still registered as a buffer so should move to device + dtypes accordingly

## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)

### Screenshots

# Checklist:

- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] I have not rewritten tests relating to key interfaces which would affect backward compatibility

2023-06-11 21:13 UTC, ArthurConmy commented
@neelnanda-io are you looking for someone to add the tests and docs? Or a review on this? CC @curt-tigges and others blocked

2023-06-12 22:34 UTC, ArthurConmy requested changes
Please also make this update to `HookedEncoder` (used for BERT):

https://github.com/neelnanda-io/TransformerLens/blob/c268a7159a6f8d5c78236a3f958f2d704fbc940f/transformer_lens/HookedEncoder.py#L123

2023-06-13 09:10 UTC, neelnanda-io commented
Change made

2023-06-13 12:02 UTC, ArthurConmy commented on transformer_lens/HookedEncoder.py
>              * repeat(1 - one_zero_attention_mask, "batch pos -> batch 1 1 pos")
You need to replace the additive attention_mask definition with this one --- sorry didn't realize this first time!

2023-06-20 02:11 UTC, jbloomAus commented
@ArthurConmy Maybe we can get someone who isn't Neel to finish this? Maybe an ARENA student?

2023-10-04 11:51 UTC, ArthurConmy commented
Superseded by https://github.com/neelnanda-io/TransformerLens/pull/366

2023-10-04 11:51 UTC, closed without merging