Fix tokenization in utils.test_prompt
neelnanda-io/TransformerLens pull request #334
Opened 2023-07-02 13:07 UTC by Felhof

# Description

Fixes #271. Before, test_prompt would throw an index error when the concatenated prompt and answer string had a different tokenization from the prompt and answer strings separately. The function now works for such cases. I also added a unit test checking that the issue is handled correctly.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

2023-07-05 22:50 UTC, jbloomAus commented
@Felhof it seems like there's too many commits here / lots of files changed making it hard to review, can you branch off main with just the relevant changes and then resubmit please?

2023-07-26 13:36 UTC, jbloomAus submitted a review, later dismissed
Hey @Felhof,

Testing via console output feels icky. Is there no way to make this test operate on python objects?

2023-10-06 15:29 UTC, Felhof commented
Ok I reimplemented the test, so it mocks the print calls and asserts on the calls to make sure the correct values are printed.

2023-10-12 23:38 UTC, alan-cooney requested changes
Nice work on this - I've added some suggestions to make the tests much more readable.

2023-10-12 23:38 UTC, alan-cooney commented on tests/unit/test_utils.py
> +    "prepend_space_to_answer, expected_print_calls, expected_rprint_calls",
I think you are checking that it tokenises correctly here? 

```suggestion
    "prepend_space_to_answer, tokenized_prompt, tokeized_answer",
```

I'd suggest changing to this ^ and then just putting the array in directly. The `call()` part can be done in the test.

2023-10-12 23:38 UTC, alan-cooney commented on tests/unit/test_utils.py
> +        assert received_call == expected_call
I don't think this is needed (and it's best practice to just test one thing/feature in a test - in this case tokenisation).

```suggestion
```

2023-10-12 23:38 UTC, alan-cooney commented on tests/unit/test_utils.py
> +        assert received_call == expected_call
You can now just check the first 2 calls

2023-10-12 23:40 UTC, alan-cooney commented
Oh and worth adding a comment to the test explaining why it's a good check - that you might otherwise expect it to tokenize the end of the prompt with the answer as one token otherwise, which is bad.

2023-10-14 12:58 UTC, alan-cooney approved these changes
Thanks for the PR!

2023-10-14 23:58 UTC, merged