Improving attention masking and key-value caching.
neelnanda-io/TransformerLens pull request #386
Opened 2023-09-26 17:30 UTC by UFO-101

# Description

- Support passing in multiple tokens when using `past_kv_cache`.
- Change `left_attention_mask` to `attention_mask`. Update `apply_causal_mask` to support arbitrary masking (and do it faster). This means that caching 'just works' regardless of padding. So you don't need to think carefully about, for example, caching keys and values for a batch of tokens and then running a left padded batch of tokens.
- Add tests for `past_kv_cache`.
- Add `test_pos_embed_with_cache` in `test_left_padding`.
- Add documentation for `past_kv_cache`.
- Fix type hints for some components that assume `attention_mask` has same number of tokens as input. This was previously unnoticed because there were no tests that covered `past_kv_cache`.
- Support freezing key-value caches.
- Integrate `past_attention_mask` into HookedTransformerKeyValueCache so that it doesn't need to managed manually.

## Motivation for allowing multiple tokens to run with key value cache

In ACDC we run the same prompt many times. Patching only affects token positions after the point where the clean and corrupt prompts differ. We want to run the first part of the prompt that is identical between clean and corrupt, freeze the cache, then pass in only the tokens after the point of divergence for our patched runs.

## Breaking change

Removes `past_left_attention_mask` from `HookedTransformer.forward()` because the `left_attention_mask` of previous inputs is stored automatically by `HookedTransformerKeyValueCache`. I think this won't break many people's code as this argument was only added 3 weeks ago in #344. And the fix should be quite trivial as it only requires deleting this input. (See changes to tests in commit 3 for an example).

Overall I think the benefits are worth the cost as this makes caching easier to do and generally reduces complexity. I can't think of any case where someone would want to pass in a `past_left_attention_mask` that doesn't match `past_kv_cache`.

Renames left_left_attention_mask to attention_mask. This was introduced 2 weeks ago in #382, so should be fine.

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I have not rewritten tests relating to key interfaces which would affect backward compatibility

2023-09-26 22:25 UTC, UFO-101 commented
This is ready for review 👍

2023-10-10 19:22 UTC, jbloomAus commented
@UFO-101 , rebased but formatter is annoying. Don't worry about this, I'll fix before I merge (should be tomorrow morning).

2023-10-12 23:21 UTC, alan-cooney commented
> @UFO-101 , rebased but formatter is annoying. Don't worry about this, I'll fix before I merge (should be tomorrow morning).

Just to check - is this due to the changes I made to VSCode settings? It doesn't do this on my end, but if it is let me know and I'll take a look/open an issue.

2023-10-13 09:16 UTC, alan-cooney requested changes
@UFO-101 if you're happy to rebase onto the latest repo please do that and then give me a nudge, and I'll do the final review if @jbloomAus is busy.

2023-10-13 22:30 UTC, UFO-101 commented
@alan-cooney Done rebase

2023-10-14 16:45 UTC, jbloomAus commented
I'm happy with this. Can't accept since @alan-cooney you have requested changes.

2023-10-15 23:32 UTC, alan-cooney approved these changes

2023-10-15 23:33 UTC, merged