Miscellaneous changes
neelnanda-io/TransformerLens pull request #418
Opened 2023-10-16 00:37 UTC by UFO-101

# Description

- Change name of parameters from `prepend_bos` to `prepend_bos_override` and from `padding_side` to `padding_side_override` in several functions. Right now it's too easy to miss that there is `model.cfg.default_prepend_bos` and `model.cfg.default_padding_side` and the parameters in most functions are only intended for particular cases where you want to override these defaults (this was introduced recently in PR #344).
- Return the current residual when `stop_at_layer` is not None.
- Remove unnecessary arguments in implementation of `generate()`.

## Breaking changes

- Renames `prepend_bos` and `padding_side` parameters in all functions. This may break some setups. I think the recently introduced `padding_side` in particular is likely to be misused by some users because it is not documented that it is only an override.

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

# Checklist:

- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I have not rewritten tests relating to key interfaces which would affect backward compatibility

2023-10-17 08:18 UTC, alan-cooney commented
I think a better approach may be to just make this clear in the docstring, so that we don't have to release a breaking change. As long as the title is e.g. "Override Default for Prepend BOS" it's fairly clear.

The other changes seem good but mind splitting into separate PRs so we can keep the commit history clean?

2023-10-17 08:18 UTC, alan-cooney requested changes
I think a better approach may be to just make this clear in the docstring, so that we don't have to release a breaking change. As long as the title is e.g. "Override Default for Prepend BOS" it's fairly clear.

The other changes seem good but mind splitting into separate PRs so we can keep the commit history clean?

2023-10-17 20:33 UTC, UFO-101 commented
@alan-cooney Undid parameter renaming and added / updated docstrings instead.

Moved other changes into new PRs #420 and #421

2023-10-17 22:05 UTC, neelnanda-io commented
+1 to not rename the parameters, and just update the docs

2023-10-19 12:33 UTC, alan-cooney approved these changes
We're going to add some more standards for docstrings shortly, but approving now and will make some tweaks once those are added.

2023-10-19 12:34 UTC, merged